"""empty message

Revision ID: 66cd67941b4a
Revises: d051b625695b
Create Date: 2024-05-05 21:01:52.654418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cd67941b4a'
down_revision = 'd051b625695b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
